module Visual_Board
    WHITE_CHESS_KING = " \u2654 "
    WHITE_CHESS_QUEEN = " \u2655 "
    WHITE_CHESS_ROOK = " \u2656 "
    WHITE_CHESS_BISHOP = " \u2657 "
    WHITE_CHESS_KNIGHT = " \u2658 "
    WHITE_CHESS_PAWN = " \u2659 "

    BLACK_CHESS_KING = " \u265A "
    BLACK_CHESS_QUEEN = " \u265B "
    BLACK_CHESS_ROOK = " \u265C "
    BLACK_CHESS_BISHOP = " \u265D "
    BLACK_CHESS_KNIGHT = " \u265E "
    BLACK_CHESS_PAWN = " \u265F "

    CHESSBOARD_LABEL = "\e[36m    a  b  c  d  e  f  g  h \e[0m"

    BACKGROUND_LIGHT_CYAN = 106
    BACKGROUND_LIGHT_RED = 101
    BACKGROUND_CYAN = 46
    BACKGROUND_LIGHT_GRAY = 47
    BACKGROUND_DARK_GRAY = 100
end